# Generated by Django 6.0.6 on 2026-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
