# Generated by Django 6.0.6 on 2026-06-23 18:18

import appointments.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('preferred_date', models.DateField(validators=[appointments.models.validate_not_past])),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('budget_range', models.CharField(choices=[('UNDER_500', 'Under 500'), ('500_TO_2000', '500 to 2000'), ('2000_TO_5000', '2000 to 5000'), ('OVER_5000', 'Over 5000')], default='UNDER_500', max_length=50)),
                ('project_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ('-created_at',),
            },
        ),
    ]
