# Generated by Django 6.0.6 on 2026-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='singleton_enforcer',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='x',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
